import { chromium } from "playwright";
const b = await chromium.launch({ headless: true });
const p = await b.newPage({ viewport: { width: 1360, height: 900 } });
await p.goto("http://localhost:8993/");
await p.waitForURL(/auth\/login/);
await p.fill('input[name="email"]', "e2e@example.com");
await p.fill('input[name="password"]', "e2e-pass-1");
await p.click("form button");
await p.waitForSelector(".guide");
await p.waitForTimeout(800);
const dir = "/Users/snow/.claude/jobs/31cc1f49/tmp/react-shots/";
await p.screenshot({ path: dir + "1-home-guide.png" });
await p.evaluate(() => document.getElementById("content").scrollTo(0, 1200));
await p.waitForTimeout(300);
await p.screenshot({ path: dir + "2-home-insights.png" });
const pid = (await (await p.request.get("http://localhost:8993/api/projects")).json()).projects.find(x=>x.name==="wiki").id;
await p.goto(`http://localhost:8993/${pid}/index.md`);
await p.waitForSelector("#content h1");
await p.waitForTimeout(400);
await p.screenshot({ path: dir + "3-file-view.png" });
await p.goto(`http://localhost:8993/${pid}/notes`);
await p.waitForSelector(".dl-history");
await p.waitForTimeout(400);
await p.screenshot({ path: dir + "4-folder-listing.png" });
await p.goto(`http://localhost:8993/${pid}/history`);
await p.waitForSelector(".hentry");
await p.screenshot({ path: dir + "5-history.png" });
await p.click("#invite-btn");
await p.waitForSelector(".admin");
await p.waitForTimeout(400);
await p.screenshot({ path: dir + "6-org-admin.png" });
await p.keyboard.press("Meta+k");
await p.waitForSelector("#palette");
await p.fill("#palette-input", "read");
await p.waitForTimeout(300);
await p.screenshot({ path: dir + "7-palette.png" });
// mobile viewport
const m = await b.newPage({ viewport: { width: 390, height: 780 } });
await m.goto(`http://localhost:8993/${pid}/index.md`);
await m.waitForSelector("#content h1");
await m.screenshot({ path: dir + "8-mobile-file.png" });
await b.close();
console.log("shots done");
