import { test, expect, Page, FrameLocator } from "@playwright/test";
import { login, ADMIN, READER } from "./helpers";

/* Click-to-edit on a synced HTML file, end to end: the real hub, the real
   stamper, the real ProseMirror mounted inside the real sandboxed iframe.

   The assertion that matters is never "the text on screen changed" — it is
   what the FILE looks like afterwards. Every test here reads the stored bytes
   back and checks that only the edited element moved. A visual editor that
   quietly reformats a teammate's document is the failure this feature exists
   to avoid, and it looks perfectly fine in the browser. */

/* Every test makes its own file, and nothing is added to the shared seed.

   Two separate reasons, both learned the hard way:

   - These specs share one hub, so an idle save from the previous test landing
     in the middle of the next one fails a test that has nothing wrong with it.
   - Adding one file to the seeded project destabilised EIGHT unrelated specs.
     The extra row shifts the shell's timing just enough to expose a latent bug
     in the account menu (it needs two clicks to reopen after the org is
     renamed — AccountBar.tsx, nothing to do with editing). Seed data is shared
     state; growing it makes every other spec pay. */
const FIXTURE = `<!DOCTYPE html>
<html>
  <head>
    <title>Quarterly report</title>
    <style>body { font-family: system-ui; }</style>
  </head>
  <body>
    <!-- generated by the reporting agent -->
    <h1>Quarterly report</h1>
    <p class="lead">Revenue grew steadily across every region.</p>
    <p>See the <a href="/notes/readme.md">notes</a> for the method.</p>
    <p>Margin was <span class="badge">up 4%</span> on the quarter.</p>
    <p>First line<br>second line.</p>
    <ul>
      <li>North America led the quarter.</li>
      <li>EMEA recovered in March.</li>
    </ul>
    <pre><code>  indented
  code</code></pre>
    <script>console.log("chart would render here");</script>
  </body>
</html>
`;

let n = 0;

/* These specs work in a project of their OWN, not the seeded "wiki".

   Editing writes files, and writing files to a shared project is shared state:
   the tree, the dashboard and the run cards all read it. Adding files there
   broke four session-run specs, and removing them afterwards broke them
   differently — the removals are themselves changes in the feed. A separate
   project is the only version of this that leaves the rest of the suite
   exactly as it found it.

   Its default level is READ, which costs nothing here and buys the read-only
   test a subject: the admin is the org owner and so still resolves to admin,
   while an ordinary member gets read. */
const PROJECT = "inline-edit-e2e";
let projectId = "";

async function project(page: Page): Promise<string> {
  if (projectId) return projectId;
  const r = await page.request.post("/api/projects", { data: { name: PROJECT } });
  expect(r.ok()).toBeTruthy();
  projectId = (await r.json()).project.id;
  const perm = await page.request.put(`/api/p/${projectId}/permissions`, {
    data: { default: "read" },
  });
  expect(perm.ok()).toBeTruthy();
  return projectId;
}

/* A private copy of the fixture, written through the same upload route the
   editor saves with — and removed again when the test ends.

   Removing it matters even inside a project of our own. The app's shell reads
   the whole world it can see, and this suite shares one hub: every file left
   behind makes the sidebar a little taller and the next spec's timing a little
   different. Unrelated specs have already been knocked over twice by exactly
   that. A spec that adds to the world puts it back. */
async function ownFile(page: Page, id: string): Promise<string> {
  const name = `edit-${Date.now()}-${n++}.html`;
  const r = await page.request.put(
    `/api/p/${id}/upload/content?path=${encodeURIComponent(name)}`,
    { data: FIXTURE, headers: { "Content-Type": "text/plain; charset=utf-8" } },
  );
  expect(r.ok()).toBeTruthy();
  litter.push(async () => {
    await page.request
      .post(`/api/p/${id}/remove`, { data: { path: name } })
      .catch(() => {});
  });
  return name;
}

const litter: (() => Promise<void>)[] = [];

test.afterEach(async () => {
  while (litter.length) {
    try {
      await litter.pop()!();
    } catch {
      /* the hub outlives the test either way */
    }
  }
});

async function openEditor(
  page: Page,
): Promise<{ id: string; file: string; frame: FrameLocator }> {
  const id = await project(page);
  const name = await ownFile(page, id);
  await page.goto(`/${id}/${name}`);
  await page.click("#edit-btn");
  const frame = page.frameLocator("iframe.htmlview");
  // NOT [data-bd-src]: those come with the served HTML, so they are on screen
  // before the bootstrap has loaded and can be clicked before anything is
  // listening. data-bd-ready is set by the script itself, so it is the only
  // wait that means "editable" rather than "rendered".
  await frame.locator("html[data-bd-ready]").waitFor();
  return { id, file: name, frame };
}

async function source(page: Page, id: string, file: string): Promise<string> {
  const r = await page.request.get(
    `/api/p/${id}/file?path=${encodeURIComponent(file)}`,
  );
  expect(r.ok()).toBeTruthy();
  return r.text();
}

/* A save travels through TWO 700ms idles — the editor's, then the shared
   document's — before the hub has the bytes. Sleeping for "long enough" put a
   race in every test here; polling states what is actually being waited for.

   waitForSource is for an edit that must land, expectUnchanged for one that
   must not. The second cannot poll for an absence, so it pays the wall-clock
   wait once. */
async function waitForSource(page: Page, id: string, file: string, want: string) {
  await expect
    .poll(() => source(page, id, file), { timeout: 10_000, intervals: [200] })
    .toEqual(expect.stringContaining(want));
  return source(page, id, file);
}

async function expectUnchanged(page: Page, id: string, file: string, before: string) {
  await page.waitForTimeout(2500); // both idles, plus room for the write
  expect(await source(page, id, file)).toBe(before);
}

test("editing a paragraph rewrites only that paragraph", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);
  const before = await source(page, id, file);

  const lead = frame.locator("p.lead");
  await lead.click();
  await page.keyboard.press("End");
  await page.keyboard.type(" Especially EMEA.");

  const after = await waitForSource(
    page,
    id,
    file,
    "Revenue grew steadily across every region. Especially EMEA.",
  );
  expect(after).not.toBe(before);

  // The whole point: everything outside the edited element is byte-identical.
  // Indentation, the comment, the <style>, the <script>, the <pre> — an agent
  // re-reading this file has to find what it wrote.
  expect(after).toContain("<!-- generated by the reporting agent -->");
  expect(after).toContain("<style>body { font-family: system-ui; }</style>");
  expect(after).toContain('<script>console.log("chart would render here");</script>');
  expect(after).toContain("<pre><code>  indented\n  code</code></pre>");
  expect(after).toContain('<a href="/notes/readme.md">notes</a>');
  expect(after).toContain("<!DOCTYPE html>");

  // And the diff really is one line, not a reformat that happens to contain
  // the right words.
  const changed = after
    .split("\n")
    .filter((l, i) => l !== before.split("\n")[i]);
  expect(changed).toHaveLength(1);
});

test("Cmd+B wraps the selected word in <strong>", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  /* Selected by double-click — a word, the way a person selects one.

     Not Home + Shift+ArrowRight: ProseMirror syncs the DOM selection to its
     own state asynchronously, and keystrokes driven over CDP outrun that sync,
     so Cmd+B arrives while the editor still believes the caret is collapsed
     and quietly does nothing. A double-click settles the selection before the
     shortcut is pressed. */
  const li = frame.locator("li").first();
  await li.dblclick({ position: { x: 12, y: 8 } });
  await expect
    .poll(() => frame.locator("li").first().evaluate(() => String(getSelection())))
    .not.toBe("");
  await page.keyboard.press(
    process.platform === "darwin" ? "Meta+b" : "Control+b",
  );

  const after = await waitForSource(page, id, file, "<strong>North</strong>");
  // The sibling list item is untouched.
  expect(after).toContain("<li>EMEA recovered in March.</li>");
});

/* Inline markup the schema has no node for is CARRIED THROUGH, not refused.

   This started life as the opposite test: a <span class="badge"> could not be
   represented, so the paragraph would not open at all. That is safe and it is
   useless — real prose is full of spans, links and <sup>, and an editor that
   refuses every paragraph containing one mostly says no. The passthrough mark
   keeps the tag and its attributes verbatim, so the span survives an edit to
   the text around it. */
test("unusual inline markup survives an edit instead of blocking it", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  const badge = frame.locator("p", { hasText: "Margin was" });
  await badge.hover();
  await expect(badge).toHaveAttribute("data-bd-edit", "yes");
  await badge.click();
  // Typed wherever the click landed. Asserting on caret POSITION would be
  // asserting on ProseMirror's asynchronous selection sync, which keystrokes
  // driven over CDP routinely outrun — and position is not what this is about.
  await page.keyboard.type("CONFIRMED");

  const after = await waitForSource(page, id, file, "CONFIRMED");
  // The span and its class come back byte-for-byte.
  expect(after).toContain('<span class="badge">up 4%</span>');
});

/* A link is the case this most had to get right.

   TipTap's Link extension re-renders an anchor from its own defaults, adding
   target="_blank" and rel="noopener noreferrer nofollow" that the file never
   had — so the round trip failed and EVERY paragraph containing a link was
   refused, which is most prose in a real document. Links are carried through
   verbatim now; this pins the href surviving untouched. */
test("a paragraph containing a link is editable and the link is untouched", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  const para = frame.locator("p", { hasText: "See the" });
  await expect(para).toHaveAttribute("data-bd-src", /\d+,\d+/);
  await para.hover();
  await expect(para).toHaveAttribute("data-bd-edit", "yes");
  await para.click({ position: { x: 12, y: 8 } });
  await page.keyboard.type("LINKEDIT");

  const after = await waitForSource(page, id, file, "LINKEDIT");
  expect(after).toContain('<a href="/notes/readme.md">notes</a>');
  expect(after).not.toContain("noopener");
  expect(after).not.toContain('target="_blank"');
});

/* The gate is still there, and still refuses what it genuinely cannot carry.

   <br> has no node in this schema, so a paragraph containing one cannot be
   serialized back unchanged. Refusing it is the correct answer and the reason
   the check survives the passthrough: the passthrough widens what is editable,
   it does not remove the last line of defence. */
test("markup the schema still cannot carry is refused", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);
  const before = await source(page, id, file);

  const br = frame.locator("p", { hasText: "First line" });
  await br.hover();
  await expect(br).toHaveAttribute("data-bd-edit", "no");
  await br.click();
  await page.keyboard.type("must not land");

  await expectUnchanged(page, id, file, before);
  expect(await source(page, id, file)).toContain("First line<br>second line.");
});

/* Clicking from one paragraph to the next must leave the first one ON SCREEN.

   ProseMirror empties a mounted element when the view is destroyed — its
   destroy() ends with `dom.textContent = ""` whenever {mount} was used, on the
   assumption that the owner re-renders. Nothing re-renders the page's own
   markup here, so every paragraph vanished as soon as you clicked away from
   it. The file was fine the whole time, which made it worse: it looked exactly
   like the editor eating your document.

   Asserting the FILE is not enough for this one. The bug was only ever visible
   on screen. */
test("an edited paragraph stays on screen after clicking another", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  const first = frame.locator("p.lead");
  await first.click();
  await page.keyboard.type("ONE");
  const second = frame.locator("p", { hasText: "See the" });
  await second.click();
  await page.keyboard.type("TWO");
  await frame.locator("h1").click();

  // Both still rendered, both still holding their text.
  await expect(first).toContainText("Revenue grew steadily");
  await expect(first).toContainText("ONE");
  await expect(second).toContainText("for the method");
  await expect(second).toContainText("TWO");
  // And the element is not left as an empty shell.
  expect((await first.innerHTML()).trim()).not.toBe("");

  const after = await waitForSource(page, id, file, "TWO");
  expect(after).toContain("ONE");
});

/* Typing and pressing Done straight away must keep the edit.

   This is what finishing an edit looks like, and it used to lose the text.
   The iframe debounced its patch by 700ms, so for that window the edit existed
   ONLY inside the iframe — and Done tears the iframe down. The patch never
   reached the document, the save saw nothing to write, and the reader went
   back to a page that had silently discarded what they typed.

   No pause here on purpose. A test that waits cannot see this bug; every
   earlier test in this file waited, which is exactly why it shipped. */
test("an edit survives pressing Done immediately after typing", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  await frame.locator("p.lead").click();
  await page.keyboard.type("NOPAUSE");
  await page.click("#edit-btn"); // Done, with nothing in between

  const after = await waitForSource(page, id, file, "NOPAUSE");
  expect(after).toContain("<!DOCTYPE html>");
  // And the reader is looking at the saved file, not a stale render.
  await expect(
    page.frameLocator("iframe.htmlview").locator("p.lead"),
  ).toContainText("NOPAUSE");
});

test("Enter and Backspace cannot restructure the document", async ({ page }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);
  const before = await source(page, id, file);

  const lead = frame.locator("p.lead");

  // Enter is swallowed wherever the caret is, so this needs no positioning.
  await lead.click();
  await page.keyboard.press("Enter");

  /* Backspace only means "merge with what came before" AT THE START, so the
     caret has to genuinely be there. Clicking the left edge and then WAITING
     for the browser to report a collapsed selection at offset 0 is the only
     reliable way: ProseMirror syncs the DOM selection asynchronously, so a
     Backspace sent too early lands mid-word and deletes a real character —
     which is a perfectly good edit, and nothing to do with what is being
     tested here. */
  await lead.click({ position: { x: 1, y: 8 } });
  await expect
    .poll(() =>
      lead.evaluate(() => {
        const s = getSelection();
        return !!s && s.isCollapsed && s.anchorOffset === 0;
      }),
    )
    .toBe(true);
  await page.keyboard.press("Backspace");

  // No new element, no merged element, no change at all.
  await expectUnchanged(page, id, file, before);
});

// Text inside <script>, <style> and <pre> is not prose, and the server never
// marks it. This is the line between "editing a document" and "editing code
// that happens to be in the same file".
test("script, style and pre are never clickable", async ({ page }) => {
  await login(page, ADMIN);
  const { frame } = await openEditor(page);

  for (const sel of ["script", "style", "pre", "title"]) {
    await expect(frame.locator(`${sel}[data-bd-src]`)).toHaveCount(0);
  }
  // Nor is a container whose text lives in its children.
  await expect(frame.locator("body[data-bd-src], ul[data-bd-src]")).toHaveCount(0);
  // But the prose is.
  await expect(frame.locator("p.lead[data-bd-src]")).toHaveCount(1);
  await expect(frame.locator("h1[data-bd-src]")).toHaveCount(1);
});

// The sandbox is what lets the hub render synced HTML at all. Editing must not
// buy a single extra capability — allow-same-origin here and every synced page
// is running with the reader's session.
test("the editing iframe keeps the reading sandbox", async ({ page }) => {
  await login(page, ADMIN);
  await openEditor(page);
  const sandbox = await page.locator("iframe.htmlview").getAttribute("sandbox");
  expect(sandbox).toBe("allow-scripts");
});

test("a read-only member is not offered the editor", async ({ page, browser }) => {
  // The file has to exist before a reader can be refused it, and a reader
  // cannot create one — so an admin makes it in a context of their own rather
  // than by adding to the shared seed.
  const admin = await browser.newContext();
  const ap = await admin.newPage();
  await login(ap, ADMIN);
  const id = await project(ap);
  const file = await ownFile(ap, id);
  await admin.close();

  await login(page, READER);
  await page.goto(`/${id}/${file}`);
  await page.locator("iframe.htmlview").waitFor();
  // Same rule Share follows: no button, rather than a button that 403s.
  await expect(page.locator("#edit-btn")).toHaveCount(0);
  // And the render they do get has nothing to click.
  await expect(
    page.frameLocator("iframe.htmlview").locator("[data-bd-src]"),
  ).toHaveCount(0);
});

/* Two people in one file at once — the claim the whole CRDT design exists for.

   It is also the only test that exercises the relative positions. The second
   editor's ranges were measured against the file as it was when its iframe
   rendered; the first editor's save moves every byte after the paragraph it
   touched. If those ranges were plain offsets, the second edit would land in
   the middle of somebody else's markup, and it would do so silently. */
test("two people editing different paragraphs both land", async ({ page, browser }) => {
  await login(page, ADMIN);
  const { id, file, frame } = await openEditor(page);

  const other = await browser.newContext();
  const op = await other.newPage();
  await login(op, ADMIN);
  await op.goto(`/${id}/${file}`);
  await op.click("#edit-btn");
  const oframe = op.frameLocator("iframe.htmlview");
  await oframe.locator("html[data-bd-ready]").waitFor();

  // First window edits the lead paragraph, which sits BEFORE the list — so
  // every later offset in the file shifts under the second window's feet.
  await frame.locator("p.lead").click();
  await page.keyboard.press("End");
  await page.keyboard.type(" Especially EMEA.");
  await waitForSource(page, id, file, "region. Especially EMEA.");

  // Second window edits a list item, using ranges measured before that shift.
  await oframe.locator("li").first().click();
  await op.keyboard.press("End");
  await op.keyboard.type(" Strongly.");
  const after = await waitForSource(op, id, file, "quarter. Strongly.");
  await other.close();

  // Both edits survive, each in its own element, and nothing in between moved.
  expect(after).toContain("region. Especially EMEA.");
  expect(after).toContain("<li>North America led the quarter. Strongly.</li>");
  expect(after).toContain("<li>EMEA recovered in March.</li>");
  expect(after).toContain('<script>console.log("chart would render here");</script>');
});

/* A file that is not in English, edited through the whole real stack.

   The offsets the server stamps are UTF-16 code units, because that is how a
   JS string — and so the Y.Text they are resolved against — is indexed. Count
   them in bytes and every range after the first accented character is wrong,
   and the edit is written over the middle of neighbouring markup. Go tests
   cover the counting; this is the one that proves the client agrees, with real
   ProseMirror and a real save.

   The emoji is doing a job: it is 4 bytes and TWO UTF-16 units, so it also
   rules out "count runes instead", which is the obvious wrong fix. */
test("a non-ASCII document edits without corrupting its neighbours", async ({ page }) => {
  await login(page, ADMIN);
  const id = await project(page);
  const name = `i18n-${Date.now()}.html`;
  const src = `<!DOCTYPE html>
<html>
  <body>
    <h1>四半期レポート 🚀</h1>
    <p class="lead">Chiffre d'affaires en hausse — très bien.</p>
    <p>Marge stable sur le trimestre.</p>
    <p>日本語のテキストもあります。</p>
  </body>
</html>
`;
  const put = await page.request.put(
    `/api/p/${id}/upload/content?path=${encodeURIComponent(name)}`,
    { data: src, headers: { "Content-Type": "text/plain; charset=utf-8" } },
  );
  expect(put.ok()).toBeTruthy();

  await page.goto(`/${id}/${name}`);
  await page.click("#edit-btn");
  const frame = page.frameLocator("iframe.htmlview");
  await frame.locator("html[data-bd-ready]").waitFor();

  // The LAST paragraph: every preceding line has multi-byte characters, so a
  // byte-counted offset would land somewhere else entirely.
  await frame.locator("p", { hasText: "日本語" }).click();
  await page.keyboard.press("End");
  await page.keyboard.type("追記。");

  /* Asserted WITH its tags, and with the file's shape checked after.

     Looking for the edited text alone is not enough, and this is not
     hypothetical: with byte offsets the range resolves past the end of the
     document, so the patch is appended after </html> — where the file still
     "contains" the expected string, every neighbour is still intact, and a
     substring assertion passes against a thoroughly corrupted file. */
  const after = await waitForSource(
    page,
    id,
    name,
    "<p>日本語のテキストもあります。追記。</p>",
  );
  // Every neighbour is untouched, including the emoji and the em dash.
  expect(after).toContain("<h1>四半期レポート 🚀</h1>");
  expect(after).toContain(`<p class="lead">Chiffre d'affaires en hausse — très bien.</p>`);
  expect(after).toContain("<p>Marge stable sur le trimestre.</p>");
  expect(after).toContain("<!DOCTYPE html>");
  // Nothing was appended past the document, and nothing was duplicated.
  expect(after.trimEnd().endsWith("</html>")).toBe(true);
  expect(after.split("日本語").length - 1).toBe(1);
});

// The escape hatch. Click-to-edit deliberately cannot add a section or repair
// a tag, so there has to be a way down to the markup.
test("Edit source drops to the markup editor and back", async ({ page }) => {
  await login(page, ADMIN);
  await openEditor(page);

  await page.click("#edit-source-btn");
  await expect(page.locator("#editor")).toBeVisible();
  await expect(page.locator("iframe.htmlview")).toHaveCount(0);

  await page.click("#edit-source-btn");
  await expect(page.locator("iframe.htmlview")).toBeVisible();
});

test("leaving edit mode returns the page to plain reading", async ({ page }) => {
  await login(page, ADMIN);
  const { frame } = await openEditor(page);
  await expect(frame.locator("p.lead[data-bd-src]")).toHaveCount(1);

  await page.click("#edit-btn"); // "Done"
  await expect(
    page.frameLocator("iframe.htmlview").locator("[data-bd-src]"),
  ).toHaveCount(0);
});
